### ISSUE TITLE
Adding alt/title support for SEO purposes

### ISSUE THREAD

**Issue by simonwalsh** [afklm/ng-lazy-image#10]
Hey guys!

Was wondering if it were possible to add alt/title support for SEO? 

We could either have those directly on the `div` tag (but not very semantic) or have them has a `data` attribute. Could also be added to the options array, but it might be a bit messy for long strings.

If you see this as a good idea, I can prepare a pull request.

Keep me posted!

**Comment by SquadraCorse** [comment]
We thought about alternative content and wether it should replace it or not (also take notice we have background images as well). I think alternative title as data attribute is ok since image itself is written with js as well. So now in bower latest. Thanks!

**Comment by simonwalsh** [comment]
Thanks for fast response time man! Will try that out tomorrow :)
