### ISSUE TITLE
Modify existing <img> tag instead of appending one

### ISSUE THREAD

**Issue by ObaidUrRehman** [afklm/ng-lazy-image#13]
Is it possible to use the `afkl-lazy-image` directive in an image tag? Right now it creates a new image tag and appends it. I need this because my CSS does not get applied because of this DOM change.

I can probably take a stab at it.

**Comment by SquadraCorse** [comment]
Do you have an example somewhere to show "CSS does not get applied"? The "problem" with a real image tag is that you need a src with a reference to begin with, and the setup at the moment should be realy flexible.

**Comment by ObaidUrRehman** [comment]
I have a CSS hierarchy that is goes some thing like this:

    td.img {
       width: 100px;
       height: 100px;
    }

I am not using `<div>` inside the `<td>` so the `<img>` tag is not getting the style. I can probably use the `afkl-lazy-image` directive on the `<td>` but I'd like to keep my html structure the same.

Any way, having said that, I am cool with the current way. But having an option to not replace it would have been nice too. Kinda like how `ng-src` directive works.

**Comment by SquadraCorse** [comment]
Ok, just style the "td" in this case in these dimensions (by giving it a class), the image has css with it setting width to 100% on the container it has. Then if aspect ratio of image is 1-1 as well it will be filling your container.

**Comment by SquadraCorse** [comment]
.afkl-lazy-image {
	width: 100%;
}
