### ISSUE TITLE
Question: Promise when -all- images are loaded

### ISSUE THREAD

**Issue by michaelrachlitz** [afklm/ng-lazy-image#14]
Hi,

I have a project where I would like to display a preloader on the page until all images and AJAX requests have been fully loaded.

Is there already a feature or a modification I could make (maybe a broadcast) that could help me achieve this easily with ng-lazy-image?

Sorry if this in an inapropriate forum to ask this question.

Kindly,
Michael

**Comment by azizantoun** [comment]
I'm facing the same problem. Still couldn't find a good solution

**Comment by SquadraCorse** [comment]
So you actually don't lazy load them but while giving loading state? If so a simpler directive can be made i think. I can add broadcasting but then the directive itself should know if it is part of a group... 

Let me think about it.

**Comment by michaelrachlitz** [comment]
Hey SandraCorse,

Exactly. Images needs to be grouped. I actually use the option {"nolazy": true}, as I don't want the images to lazy load when visible to the window, but rather load them as a group. I am not sure wether this directive is the correct one to use. But grouping them and having the broadcast as a hook would be a powerful directive. Not necessarely something ng-lazy-image should support though, I dont know. 

Thanks for looking into it and getting back to me this fast.

**Comment by SquadraCorse** [comment]
Do you use multiple sources, or single one per image? Does it need to do checks when resizing? Best setup would be making your own with an instance holding every added url and on every image loaded/errored it takes it from it until it's empty and then emits. So then you can take some parts of this directive and customize on your own needs. If i have time i can make a sample.

**Comment by michaelrachlitz** [comment]
Hi SquadraCorse (sorry I mispelled your name earlier)

Would be really cool with a sample. I load several collections of images.

ProductService, gets (among other informations) an object containing several images.
VariantService, gets objects containing several images.
ProductListService, gets objects containing several images.

I would like to load the collections of images from all services together, and display the full page when this is a succes. The resize on browser change is not important. But I do like the fact that I can provide a mobile with an image that is lower resolution to save bandwidth.

I would really appreciate a sample if you have the time.

Again thanks a lot for getting back to me so quickly.

**Comment by SquadraCorse** [comment]
See if latest addition is workable for you. You can have your own directive doing calculation which images got loading state. Maybe you need error state as well?
