### ISSUE TITLE
any way to pass ng-click into the image tag?

### ISSUE THREAD

**Issue by surfjedi** [afklm/ng-lazy-image#23]
any way to pass ng-click into the image tag?

**Comment by SquadraCorse** [comment]
Why should you? You can add that to the directive container itself right?

**Comment by surfjedi** [comment]
True could add it to container but I am trying to refactor a huge code base and we just have alot of img tags with ngsrc and the ng-click on them already..

**Comment by SquadraCorse** [comment]
This directive doesn't use ng-src, so then if you will you need to move some stuff over. Now you can choose to have seo links arround it or clickable container which makes it beter usable by only focussing on delivering the right image at the right moment.
