### ISSUE TITLE
Don't forget to update npm

### ISSUE THREAD

**Issue by sylouuu** [afklm/ng-lazy-image#32]
Hi,

https://www.npmjs.com/package/angular-lazy-image

```
0.0.11 is the latest release
```

But I can see that the latest is `0.2.2` in https://github.com/afklm/ng-lazy-image/releases.

Bests

**Comment by SquadraCorse** [comment]
oeps :( done

{code}
{ modified: '2015-10-29T17:17:13.036Z',
  created: '2015-03-07T09:24:19.053Z',
  '0.0.11': '2015-03-07T09:24:19.053Z',
  '0.2.2': '2015-10-29T17:17:13.036Z' }
{code}
