### ISSUE TITLE
Retina support?

### ISSUE THREAD

**Issue by musdy** [afklm/ng-lazy-image#35]
Hello,

Is there any way to support retina images 2x?

<div afkl-lazy-image="//placehold.it/768x768 768w, //placehold.it/768x768 768w, //placehold.it/768x768 768w 2x, //placehold.it/1280x1280" class="afkl-lazy-wrapper afkl-img-ratio-1-1"></div>

Something like this maybe?

**Comment by SquadraCorse** [comment]
it is using old srcset setup, so pixeldensity is already in it!

**Comment by musdy** [comment]
Perfect!
