### ISSUE TITLE
background: true setting not working

### ISSUE THREAD

**Issue by baffleinc** [afklm/ng-lazy-image#36]
Installed using bower @ v0.2.2, I was having trouble getting the background image to set instead of filling the element with a new img tag.

I even copied and pasted the example directly off the github.io, and that is also adding an image tag instead of setting the background image.

Any ideas?

**Comment by SquadraCorse** [comment]
Idea is to go trough the options :-)

afkl-lazy-image-options="{"background": true}"

http://afklm.github.io/ng-lazy-image/sample-background.html

**Comment by baffleinc** [comment]
Thanks - I did that, but it turned out the bower version of the package was old without the background options. I had to copy the dist file from this repo to get it working properly :) Pls update the bower package!
