### ISSUE TITLE
Trigger lazy load with $broadcast

### ISSUE THREAD

**Issue by musdy** [afklm/ng-lazy-image#38]
Hey guys,

Is there a way to trigger lazy load event with $broadcast? I have load more functionality on the page, but once the new html arrives, I need to re-trigger lazy load event. 

Thanks.

- M

**Comment by SquadraCorse** [comment]
you can 'afkl.lazyImage.destroyed'

**Comment by SquadraCorse** [comment]
since 0.2.3 :)
