### ISSUE TITLE
Browser back slowness

### ISSUE THREAD

**Issue by mmccallum** [afklm/ng-lazy-image#43]
Seem to be experiencing some slowness when using the browsers back button.  It seems that lazy-image is doing a destroy that takes a very long time.  When I have 40 lazy load images (placed using an ng-repeat) on the page, it can take up to 20 seconds after clicking the back button for the previous page to display.

Is there a preferred method of handling a browser back click that might be faster?  I assume the slowness is due to the DOM manipulation.

Thanks!
M

**Comment by SquadraCorse** [comment]
ng-route or ui-router? Heap snapshots don't show strange things. Are you sure your route is destroying old view? In chrome, run timeline record your session then see which function in your stack are troublesome.

**Comment by mmccallum** [comment]
ng-route.

Strange, when I use timeline, there is no slowness at all.  It goes back to
the previous page with no delay whatsoever.

Actually, I just tried it again with the developer console closed at there
also is no slowness.  I guess there is no issue here.  Sorry.

-M

**Comment by SquadraCorse** [comment]
No worries, next time create simply snapshots then you know where the cullprit is. Also easier to see if between both states stuff is leaking or not. Good luck!
