### ISSUE TITLE
Some images are not loaded when changing routes

### ISSUE THREAD

**Issue by smnbbrv** [afklm/ng-lazy-image#44]
Hello again guys,

when I reload the page / switch between routes (using ui-router) _onViewChange for the objects contained by $window looks to be called in a wrong time because the height it calculates is much too big.

If I simply wrap _onViewChange content with a simple $timeout (or setTimeout 0ms) it seems to be fixed.

Is there another way to fix this behavior? Maybe I do something wrong? The problem is that some images are not loaded in this case although the offset property I specify is 2 times bigger than images size.

If you need more data just let me know.

Thanks!

**Comment by smnbbrv** [comment]
By the way it happens on page reload as well

**Comment by SquadraCorse** [comment]
Thanks!

**Comment by smnbbrv** [comment]
@SquadraCorse this one is not covered by my previous pull request. Maybe I understand wrong and it is going to be fixed on 0.2.4?

I fixed it on my fork: https://github.com/smnbbrv/ng-lazy-image/commit/61a7f0c225e153772d53060da8da0bdd1f904ee3 but didn't make a pull request yet. Should I?

**Comment by barinali** [comment]
@smnbbrv as far as I can see, [smnbbrv@61a7f0c](a5f82f9850ab6ad1cc5ec0661647f0d060177cb8) is merged. I guess we can close this issue.

By the way, I've opened a [pull request](https://github.com/afklm/ng-lazy-image/pull/65) which I replaced debounce with throttle in. You may take a look at it.
