### ISSUE TITLE
TypeError: Cannot read property 'one' of undefined

### ISSUE THREAD

**Issue by stephenycchang** [afklm/ng-lazy-image#49]
Randomly, I would get this error in my console.

TypeError: Cannot read property 'one' of undefined
    at _checkIfNewImage (lazy-image.js:459)

where it's referencing the 'img' variable. 

However, the images are working fine. Should I just ignore the error?

**Comment by SquadraCorse** [comment]
never ignore errors, somewhere online?

**Comment by stephenycchang** [comment]
It seems like that on route change, the number of elements in view using the plugin would throw the error. However, when the elements load in, they're perfectly fine. 

All I have related to this code is:

app.module('....', 'afkl.lazyImage')

A sample element div I'm using is:

<div afkl-lazy-image="{{ IMGSRC }}" class="afkl-lazy-wrapper" afkl-lazy-image-options='{"className": "sampleclass"}'></div>

Is there a requirement of how the src should be loaded in?

Thanks

**Comment by fustic** [comment]
Same for me. Started with 0.2.3 version

**Comment by SquadraCorse** [comment]
link?

**Comment by rfanjul** [comment]
We have the same problem all the time. www.joiz.ch

**Comment by joiz** [comment]
http://www.joiz.de/#!/news - check the console on our site

**Comment by SquadraCorse** [comment]
Thanks joiz, why did you go live with it ;) will try to debug!

**Comment by SquadraCorse** [comment]
revert to 0.2.2
the broadcast on destroy to be able to work for people hiding/toggle stuff with ng-if now sends broadcast which is working after new view is being made

**Comment by SquadraCorse** [comment]
joiz if you have dev mode of website can you try 0.3.1 Please be aware that alt is not set anymore with alt but imgAttr ['alt': 'foo'] as mentioned in readme. But i hope this will not generate issues for your case anymore.

**Comment by bdairy** [comment]
so the temp solution now is to revert to 0.2.2??

**Comment by stephenycchang** [comment]
@bdairy 
You can specify the version in your bower.json file to "0.2.2" and run a bower install after that.

Such as :
"ng-directive-lazy-image" : "0.2.2"

[Here's a good read from SO](http://stackoverflow.com/questions/19030170/what-is-the-bower-version-syntax)

Although 0.3.1 fixed it for me as well.

**Comment by rfanjul** [comment]
@bdairy ok! let me try and I let you know! thanks!

**Comment by rfanjul** [comment]
Yes exactly I can confirm that it works properly. Thanks a lot guys!

**Comment by SquadraCorse** [comment]
thanks, and sorry :)
