### ISSUE TITLE
Unwanted 404 requests to the server when url is not provided (undefined)

### ISSUE THREAD

**Issue by manuel-di-iorio** [afklm/ng-lazy-image#52]
span(ng-show="img")
        .afkl-lazy-wrapper(afkl-lazy-image="http://url.com/{{img}}")

That's how I was hoping to resolve this issue but unfortunately this lib still makes a request when _img_ is _undefined_ 

Same issue even using `ng-show` on the directive itself.
Same, also putting the full image url in the scoped variable.

Have you any idea on how to handle this situation ? Thank you

**Comment by manuel-di-iorio** [comment]
Resolved using `ng-if`, thanks anyway ^_^

**Comment by SquadraCorse** [comment]
i just wanted to say that in your controller make sure if image not given give fallback url. But an if statement as wrapper should work too indeed. Good luck!

**Comment by manuel-di-iorio** [comment]
Thanks @SquadraCorse  but my little situation is different, I just need to not display that image when the url is not provided, but I'll keep your advice in mind for other cases ;)
