### ISSUE TITLE
Can you give an example on image state

### ISSUE THREAD

**Issue by bdairy** [afklm/ng-lazy-image#53]
Hello there.

 I want to create image statuses classes for each state on the image process. normally what I do is creating a directive called imageLoader, it simply adds a loading span during image loading, and when image is loaded it removes that span replace it with the image. or with a default error image in case of image error. and it gives default size for the image to avoid jumps.
But since now I am using your nice directive. I used your nice directive,, I managed to have a loading class, as well as default image height with the ratio class.. but I couldn't have an error handler.. tried to add imgAttrs. to handle onerror.. but it cannot see the function in the scope. check my code:

```
<div  afkl-lazy-image="{{mysrcset}}"
        class="afkl-lazy-wrapper afkl-img-ratio-4-3" 
         afkl-lazy-image-options="{imgAttrs: [{ 'class': 'thumb-image'},{'title':title},{'alt':post.title},{'no-image':''},{'onerror':'loadErrorImage()'}]}" >
	    </div>
```

I tried to add custom directive to the image,, you can see it in the attributes 'no-image' but it is not loading,, I guess because the image is added via script it wont load the directive. I wonder if there is away to watch  afkl-lazy-image-loaded attribute. .. 

Thanks for the big help

**Comment by SquadraCorse** [comment]
there are three states: false, done and fail being given by afklLazyImageLoaded. See example

https://github.com/afklm/ng-lazy-image/blob/master/sample/js/app.js

In the example page you can see this count directive in working. So you can make your own. I don't know why your example is not working, but with this you should enough pointers :) Good luck!

**Comment by SquadraCorse** [comment]
http://afklm.github.io/ng-lazy-image/sample-loaded.html

**Comment by bdairy** [comment]
Thanks for the help ;)
