### ISSUE TITLE
attributes passed to the directive don't get interpolated

### ISSUE THREAD

**Issue by sinsunsan** [afklm/ng-lazy-image#57]
Hello, 

I've got some attributes to pass to the image tag 
So I've followed your tuto

But my attributes use interpolation to get their value 
{{ fn.getBrickImTitle(brick) }} for example to get title="" of the images
It's about this site 
http://www.openbricks.io/app#!/bricks?p=1&page=1

But unfortunately, it does not seem to get interpolated. 
So probably I cannot use your directive. 

What do you think ?

**Comment by SquadraCorse** [comment]
Can't you place the title in your collection?

**Comment by sinsunsan** [comment]
Yes of course I could, but I've done that way. 

But even if I have the title in the collection object. 
I would need to do 
<img title="{{ img.title}}" \>
Or more generally use interpolation 
and this is not possible with your attributes passing feature. 

By the way I use another lib that do attributes passing and it seem to work, per aps you could get inspired it is angular x editable
https://vitalets.github.io/angular-xeditable/

**Comment by SquadraCorse** [comment]
It supports title only when it's part of your collection. Sorry.
http://afklm.github.io/ng-lazy-image/sample-alt-className.html
