### ISSUE TITLE
Cannot read property 'one' of undefined

### ISSUE THREAD

**Issue by musdy** [afklm/ng-lazy-image#58]
Hello guys,

I continuously get the error when the view is trying to change:

TypeError: Cannot read property 'one' of undefined
    at _checkIfNewImage (lazy-image.js:459)
    at lazy-image.js:523
    at angular.js:17918
    at completeOutstandingRequest (angular.js:5552)
    at angular.js:5829

Is there any reason why this is happening? Thanks for the great module.
- M

**Comment by SquadraCorse** [comment]
which version do you use?

**Comment by joiz** [comment]
for us it disappeared with version 0.3.1  - but this version lead to other problems

**Comment by musdy** [comment]
I was using afkl-lazy-image#~0.2.2

Which version should i update to? 0.2.3 or 0.3.1?

- M

**Comment by SquadraCorse** [comment]
Joiz can you name them? Musday i think it is best to take the version before :P or simply try latest.

**Comment by joiz** [comment]
Sometimes image don't appear if you scroll down on the page - we release today again with 0.2.3 so that problem will not be visible any longer - i can deploy the 0.3.1 version to staging after work tonight if it help. 

http://www.joiz.de/#!/

**Comment by musdy** [comment]
Yes I have seen that bug as well. That will be great if you can push that Joiz. Thanks in advance.

**Comment by musdy** [comment]
Hey @joiz, any update on 0.3.1's latest stable fix? I have upgraded to 0.2.3, but still have the error.
Thanks.

**Comment by bakaproject** [comment]
Any updates on this?

**Comment by divsbhalala** [comment]
I am facing issues as  TypeError: Cannot read property 'one' of undefined

**Comment by divsbhalala** [comment]
@musdy  use this one "ng-directive-lazy-image": "0.2.2", instead of  "ng-directive-lazy-image": "afkl-lazy-image#~0.2.2".

I have resolve my issues with this solutions
