### ISSUE TITLE
Lazy Loading Angular Cards

### ISSUE THREAD

**Issue by alabgold** [afklm/ng-lazy-image#63]
Hello, my site is using angular cards to hold images. They are angular material outlined in this demo: https://material.angularjs.org/latest/demo/card 
Im relatively new to angular and I was wondering if ng-lazy-image could be adapted to work on these cards?

**Comment by SquadraCorse** [comment]
Yes, cards are just directives ('md-card') and you can place this directive inside the directive itself.
