### ISSUE TITLE
when it is in ng-bind-html it

### ISSUE THREAD

**Issue by ebrahim-tadbir** [afklm/ng-lazy-image#66]
Hi i load the content as following:
`<div ng-bind-html="vm.data.full_content"></div>`

and then in the controller I have
` vm.data.full_content=$sce.trustAsHtml(data.data.full_content);`

and `vm.data.full_content` is as

`<p>some text</p><div  afkl-lazy-image="path-to/image.jpg" ></div>`

IT IS NOT WORKING FOR ME!

**Comment by SquadraCorse** [comment]
This is angular specific. Just recompile it. You can add a recompile
directive to the binding container! See
http://stackoverflow.com/questions/17417607/angular-ng-bind-html-and-directive-within-it

2016-11-14 9:04 GMT+01:00 ebrahim-tadbir <notifications@github.com>:
